### ISSUE TITLE
how to redraw chart on data change

### ISSUE THREAD

**Issue by musti2** [PredixDev/px-vis-timeseries#14]
Hi,

I am using the component like so: 
`<px-vis-timeseries id="vischart" title="{{nodeTitle}}" enable-tooltip="true" height="300" width="600" prevent-resize="false" selection-type="x" x-axis-config='{"title": "Date"}' chart-data="{{chartData}}" include-all-series=true></px-vis-timeseries>`

I then supply the data via iron-ajax and set it like so `this.chartData = data;`

The chart renders fine.

However, if the array of `this.chartData` is changed to reflect a different equipment, the chart fails to render (redraw) the points with the following error:
`Error: Invalid value for <rect> attribute x="NaN"
Error: Invalid value for <rect> attribute width="NaN"`

is there a method i'm supposed to call when the data changes with new dates and new values?

**Comment by dwarhya** [comment]
I second this.  I am pushing ad-hoc data into chartData.  I can see in the navigator (at the bottom) that the data is added (there is a small overflow of the line past the right hand side handle - see attached
<img width="861" alt="screen shot 2016-09-21 at 16 32 08" src="https://cloud.githubusercontent.com/assets/19690117/18718824/bca53dae-801c-11e6-8975-e9df540320ec.png">
) - but the chart does not redraw itself.

Should the chart redraw itself if the series config changes or the chart data changes?

**Comment by nonmetalhail** [comment]
The chart should automatically update when supplied with new data. Maybe the seriesConfig var is not updating?Please supply a gist demonstrating the issue.

**Comment by dwarhya** [comment]
I have worked around this issue by using the Polymer API to push data ... so instead of setting data into trend.chartData = [...], I instead use trend.push('trendData', [...]).  Using the Polymer API rather than the normal push ensures that Polymer will do the notification work needed for the new data to be processed.

**Comment by benoitjchevalier** [comment]
Closing this now that the issue has been resolved

**Comment by manderson23** [comment]
I'm also seeing this issue but I don't agree that it has been resolved.

@nonmetalhail suggests that updating the chart data property should be enough. In my case I'm currently using a computed binding so don't want to use Polymer APIs. I'm leaving the series config unchanged since it doesn't require an update.

If I'm replacing all the chart data I'd expect the component itself to handle it.

**Comment by nonmetalhail** [comment]
Unfortunately, there is nothing we can do if you do not want to use the Olymer API. Polymer v1.x observers will not fire without it.

**Comment by nonmetalhail** [comment]
If you aubmit a codepen demonstrating what you are doing, perhaps we can find a way around your problem. I dont fully understand why you are unable to use the Polymer APi.

**Comment by benoitjchevalier** [comment]
Hi,

is your issue that you are using bindings in HTML and hence don't want to use the Polymer API in Javascript? If that is the case could you try providing a codepen demonstrating the issue so we can have a look at improving it?

**Comment by manderson23** [comment]
OK. I see since it is an array I need to use the Polymer APIs.

Here is what I have
```
<px-vis-timeseries id="timeSeriesChart" 
                   register-location="top"
                   height="300"
                   series-config="[[_seriesConfig()]]"
                   chart-data="[[timeSeriesChartData]]"
                   register-config='{ "firstDateTimeFormat": "HH:mm:ss.SSS", "secondDateTimeFormat": "L" }'>
</px-vis-timeseries>
```
where `timeSeriesChartData` is defined as follows
```
timeSeriesChartData: {
          type: Array,
          value: function() { return [] },
          notify: true
}
```
`seriesConfig` is 
```
var config = {};
var dataSeries = {};
dataSeries.type = 'line';
dataSeries.x = 'x';
dataSeries.y = 'y';
dataSeries.xMin = 'dynamic';
dataSeries.xMax = 'dynamic';
dataSeries.yMin = 'dynamic';
dataSeries.yMax = 'dynamic';
dataSeries.name = 'name';
config.data = dataSeries;
return config;
```
I'm setting the chart data using `this.set('timeSeriesChartData', mydata);`

The first time I call this the chart renders the data correctly. 

If I then call it again with a different data set the chart renders blank except on mouse over the crosshair appears for a single point in the top left corner with a single value no matter where I move the mouse.

It looks like the chart is detecting that the data has changed but isn't rendering it for some reason.

**Comment by manderson23** [comment]
Also the chart I created for #26 uses include-all-series and default-series-config instead of series-config. It updates the chart data in the same manner and doesn't have the issue outlined above.

**Comment by benoitjchevalier** [comment]
When updating your data are you updating your seriesConfig to match the new data? (in particular "x" and "y" might be different)

**Comment by manderson23** [comment]
I have tried two cases:

1. Not updating seriesConfig
2. Updating seriesConfig. Only the name of the series changes x/y don't change from the previous.

In both cases I see the same result. Is there a requirement that both are updating and in a particular order?

**Comment by nonmetalhail** [comment]
So seriesConfig does not allow for "dynamic". That may be breaking everything...

**Comment by manderson23** [comment]
Thanks for your help. The issue was the use of dynamic. I've moved that to default-series-config and everything works as expected now.

It would be useful if this was part of the documentation. Also perhaps some more examples in the documentation would help with issues like this and #27

**Comment by benoitjchevalier** [comment]
We're in the process of improving our documentation and building tutorials for the vis framework. Please note we're only two people building the vis framework and are a bit stretched ;). This might take a bit longer before the tutorials come out.

Thanks for your feedback

**Comment by manderson23** [comment]
Completely understand. Great work from two people!
