### ISSUE TITLE
Can't display data when passed in as 2-D array

### ISSUE THREAD

**Issue by gstroup** [PredixDev/px-vis-timeseries#15]
A common data format for charting is a 2-D array: 
[ [1, 23432], [2,45645, [3,34527] ]

This format was supported in the past by the px-chart component.  It is also convenient, since the Predix Time Series service returns a similar format:
[ [1475101621807,2.79879224644952,3],[1475101650247,2.751557146416137,3],[1475101681728,2.605156004484788,3] ]

Could we add support for rendering a series of data when passed in as a 2-D array?  Writing my own converter for now, but seems like it should be part of the PX component.

**Comment by benoitjchevalier** [comment]
Hi Greg,

you can pass the data in a 2D array format to the px-vis-data-converter component, which will take care of converting it to the appropriate format. We use this specific format for performance purposes, hence the need for converting it.

Let me know if you need more guidance on the conversion process.

Cheers,
Ben

**Comment by gstroup** [comment]
FYI - I heard this same feedback from another developer today, while giving a little demo on timeseries charting.

**Comment by benoitjchevalier** [comment]
Hi Greg,

we're aware of the lack of documentation/tutorials :(. This is something we really want to improve but we have been pressed by hard deadlines on new chart types, which didn't leave us much time for documentation.

Regarding the converter here is how it currently works:

- expected Data: 
```
[{
    "myId":"Serie1",
    "myData":[
        [1464562720308,41],
        [1464571360308,170]
    ]
},{
    "myId":"Serie2",
    "myData":[
        [1464562720308,20],
        [1464571360308,63]
    ]
}]
```

So basically you will have to wrap your 2d array in an object, a give it some kind of id (optional, see at the end of my answer). Please note that "myId" and "myData" can be any strings, because they're passed as config in the data converter as seen below.

Given "oldData" the expected data to be converted and "newData" the converted one then the converter would look like:

```
<px-vis-data-converter
          data-key = "myData"
          id-key = "myId"
          original-data = '[[oldData]]'
          series-config="{{seriesConfig}}"
          chart-data="{{newData}}">
 </px-vis-data-converter>
```

You can also see that the data converter will generate a series-config that you can then use in your chart. You don't have to, but it has the basic config to match your series IDs.

In this case the output data will look like something like that:

[
    {
        x: 1464562720308,
        Serie1: 41,
        Serie2: 20
    },{
        x: 1464571360308,
        Serie1: 170,
        Serie2: 63
    }
]

please also note that you don't **have to** pass in `id-key = "myId"`. In this case the series will default to y0, y1...

Hope this helps, let me know if you have more questions
