### ISSUE TITLE
Wrapper div outwith bounds of parent px-vis-timeseries

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-vis-timeseries#29]
In both the predix-seed and my application the wrapper div is outwith the bounds of the px-vis-timeseries.

I note that this isn't the case with the example on the Predix UI pages.

Below is a screenshot of predix-seed. In the case of my application the bounds of the wrapper div is actually within the scroll bar so the chart is truncated.
![screenshot from 2016-12-06 15-27-05](https://cloud.githubusercontent.com/assets/1684641/20931360/bcdf209a-bbc8-11e6-9619-1fe80682e19e.png)

**Comment by benoitjchevalier** [comment]
Hello,

I'm not sure I fully get which bit is truncated on the screenshot, is your problem that the chart extends too much to the right?

**Comment by manderson23** [comment]
Sorry truncation refers to my application. The screenshot is of predix-seed.

In the screenshot I would expect the blue area to be completely within the orange area like in the example given in the px-vis-timeseries documentation.

**Comment by benoitjchevalier** [comment]
Will investigate as part of the new major version which includes new mechanism for sizing and positioning

**Comment by manderson23** [comment]
OK thanks. For now I can workaround with my own CSS.

**Comment by benoitjchevalier** [comment]
This is fixed in the new major version (not released yet, v5 branch)

**Comment by manderson23** [comment]
@benoitjchevalier Thanks for the update.

Is there any information about what will be in the new major version and the expected release schedule?

**Comment by benoitjchevalier** [comment]
Here's a quick, possibly non-exhaustive list of what has been done (does not include what we are currently doing or what we will do):

Timeseries
========
* removed registerLocation in favor of hideRegister and registerConfig
* allowed to split out the config options into smaller objects: registerConfig, tooltipConfig, eventConfig
* renamed enableTooltip to showTooltip for framework consistency
* fixed bug where tooltipConfig wasn't applied
* added clip path to cursor
* added cursor config
* added layers
* added lowerSVG
* changed line to line-svg
* changed dataExtents
* added the ability to redraw one serie on top of the others
* added the ability to pass a navigator config and configure navigator axis
* Updated register length to be dynamic based on if the navigator is included

Vis Framework
===========
* Upgrade to d3 4.4.x.
* Scale and axis changes:
  * Changed time scale to UTC by default.
  * Added timeLocal option for local time
* Greatly improved and simplified how chart extents are calculated:
  * chartExtents are now only dev set
  * max and mins from the seriesConfig and range pickers go to dataExtents
  * scale will use chartExtents directly and fallback on dataExtents if not present. If neither, then looks through data.
  * defaultSeriesConfig no longer has default min and maxes
* Threshold changes:
  * Added new threshold configuration similar to events
  * Changed threshold data property from chartData to thresholdData
* Added improved resize methods to chart behavior, allowing to align the chart within its svg
* Added mechanism for redrawing an SVG series on top of others
* Layers
  * Added layer generation to chart behavior
  * Added ability to generate layers for any svg element dynamically
  * modified interaction space so it doesnt clone svg
  * modified thresholds so it doesnt clone svg
  * Added an additional svg element below the canvas element on svg-canvas
* Fix placement of zoom button
* Changed px-vis-line to px-vis-line-svg for consistency
* Demo Updates:
  * updated demos with v1 changes
  * all subcomponents have an API Documentation page
* Added navigatorConfig and ability to configure chart navigator with it
* most px-vis components now only loads basic colors as opposed to basic colors + dataVis colors
* Register Changes:
  * Added margin to register height calculation
* Tooltip Changes:
  * Added auto-calculated groupings to tooltip based on number of series. Can be overwritten by devs
* Added checks to gridline to ensure it gets the svg height and number-izes margins


In general you can refer to the History.md of the appropriate branch. The branch is called 'major' on most charts, appart from vis (v1) and timeseries (v5)

We're not sure when we're going to release it, it depends on when testing can happen, somewhere between early to late february. We'll probably roll out charts consecutively, timeseries might be the last one (because we want to include multiple Y axis in its new major version). We might release a pre version earlier if people are interested in having a look at it.

**Comment by manderson23** [comment]
@benoitjchevalier thanks. Looks a good set of updates that will address #30 and maybe #31?

**Comment by benoitjchevalier** [comment]
Should do yes, #32 as well

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
