### ISSUE TITLE
# of ticks not configurable

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis-timeseries#35]
If I'm not mistaken, px-vis provides the possibility to set the number of ticks for the axis.
However I don't see any way to configure ticks on px-vis-timeseries#master (cnt & format).
Is there any other way to change the resolution of the x-axis ticks?

![screen shot 2017-01-24 at 00 44 29](https://cloud.githubusercontent.com/assets/385430/22227936/536702a0-e1ce-11e6-974d-96ca7e3a1794.png)

**Comment by nonmetalhail** [comment]
Hi, Yes, the number of ticks (and the format) should be configureable via a few different options. The key bit is that you have to pass those options to the axis via either xAxisConfig or yAxisConfig objects. 

Please see: https://github.com/d3/d3-axis/blob/master/README.md#axis_ticks
and look at the properties, `ticks`, `tickValues`, and `tickFormat`. 

For example, if you have too many ticks on the x-axis and only want 5:

```
<px-vis-timeseries
    x-axis-config='{ "ticks": 5 }' >
</px-vis-timeseries>
```

`ticks` itself is a bit funny. Whatever number you provide, d3 wont necessarily give you that number of ticks, but rather, approximately that number of ticks. So if, for instance, having 6 tick marks makes for better tick intervals, it will give you 6. If you really MUST have 5 ticks, `tickValues` is the safer approach, but then you have to manually provide an array with the values of where you want each tick.

`ticks` is also funny because, as you can see in the d3 docs, it can be used to provide both number of ticks and the tick format. If you want to use it in that way, construct your object like this:

```
    x-axis-config='{ 
        "ticks":  {
            "interval": 5,
            "format": "s"
        }
    }' >
```
If you want to use ticks with a function, like in the d3 example, `axis.ticks(d3.timeMinute.every(15));`, that I believe is not supported in the current release, but I will add it to the next major version which will come out in the next month. The trick there will be that you cannot pass a function in as JSON, so you will have to set xAxisConfig:

```
chart.set('xAxisConfig', {"ticks": Px.d3.timeMinute.every(15));
```
Note the Px.d3 which is our version which is safest to use to prevent possible version conflicts.

**Comment by davidsteinberger** [comment]
I think I got tripped up by the docs that talk about a ticks object. Thanks, makes perfect sense now!
